services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:29092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cassandra:
    image: cassandra:5.0
    ports:
      - "9042:9042"
    environment:
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 1G

  weather_ingest:
    build:
      context: ./ingestion/weather
    container_name: weather_ingest
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    environment:
      - KAFKA_BROKER=kafka:29092
      - WEATHER_SLEEP_SECONDS=30

  aq_ingest:
    build:
      context: ./ingestion/air_quality
    container_name: aq_ingest
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    environment:
      - OPENAQ_API_KEY=
      - KAFKA_BROKER=kafka:29092
      - AIR_SLEEP_SECONDS=30

  youtube_ingest:
    build:
      context: ./ingestion/youtube
    container_name: youtube_ingest
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    environment:
      - YOUTUBE_API_KEY=
      - KAFKA_BROKER=kafka:29092
      - YOUTUBE_SLEEP_SECONDS=30

  spark_job:
    build:
      context: ./spark
    container_name: spark_job
    depends_on:
      zookeeper:
        condition: service_started
      kafka:
        condition: service_healthy
      cassandra:
        condition: service_started
    environment:
      KAFKA_BROKER: "kafka:29092"
      CASSANDRA_HOST: "cassandra"
      SPARK_CHECKPOINT: "/opt/spark_checkpoints/climate_processor"
      CHECKPOINT_PATH: "/opt/spark_checkpoints/climate_processor"
      SPARK_DRIVER_MEMORY: "1g"
      SPARK_EXECUTOR_MEMORY: "1g"
      HOME: "/home/spark"
    volumes:
      - ./spark:/opt/spark/app
      - spark_checkpoints:/opt/spark_checkpoints
    user: root
    restart: "on-failure"

volumes:
  spark_checkpoints:
